importing: true
#input_file: estonia-20241031-highways-relations.osm.pbf

area_name: andorra
input_file: andorra-241113.osm.pbf

#input_file: estonia-20241031.osm.pbf
password: true
force: true
schema: test_import
target_schema: public
#style_file: resources/lua_styles/public-transport.lua
#style_file: G:\My Drive\code\road-graph-tool\resources\lua_styles\pipeline.lua
style_file: resources\lua_styles\pipeline.lua

