version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

loggers:
  filter_osm:
    level: INFO
    handlers: [console]
    propagate: False

  process_osm:
    level: INFO
    handlers: [console]
    propagate: False
  
  install_sql:
    level: INFO
    handlers: [console]
    propagate: False

root:
  level: WARNING
  handlers: [console]
