version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
  
  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: 'roadgraphtool.log'
    mode: 'w'

loggers:
  filter_osm:
    level: INFO
    handlers: [console, file] 
    propagate: False

  process_osm:
    level: INFO
    handlers: [console, file] 
    propagate: False
  
  install_sql:
    level: INFO
    handlers: [console, file] 
    propagate: False
  
  schema:
    level: INFO
    handlers: [console, file] 
    propagate: False

root:
  level: WARNING
  handlers: [console, file] 
